#include<stdio.h>
int main()
{
    int i,j,a,n,sum=0;
    scanf("%d",&n);
    if(n%2==0)
    {
        n--;
        sum++;
        a=((n+sum)/2)-1;
    }
    else
    {
        a=((n+sum)/2);
    }
    for(i=0;i<(n+sum)/2;i++)
    {
        for(j=0;j<n;j++)
        {
            if(j==(n/2)-i||j==(n/2)+i)
            {
                printf("*");
            }
            else
            {
                printf("_");
            }
        }
        printf("\n");
    }
}
